### ISSUE TITLE
Add events for tracking purposes

### ISSUE THREAD

**Issue by drramsey** [sakaicontrib/attendance#106]
Reviewing the sakai_events table, I do not see any events for the Attendance tool.  I believe it would be beneficial if there could be event tracking for adding/deleting an attendance item as well as inputting a users status for the item.

**Comment by msoupcoff** [comment]
Adding more detail to Derek's description, log for a change to a user's status should include who made the change and the value it was changed to

**Comment by ottenhoff** [comment]
I would note that logging changed values is not the normal course of action in Sakai and is a big burden on logging infrastructure. Yes, it's nice to be able to audit, but where does specific auditing of "who changed this value" stop and start?

**Comment by austin48** [comment]
if logging every change by who and when is **not** possible... many sakai tools have something like:

createddate
createdby
modifieddate
modifiedby
 
could the attendance event and/or status at least have something like that?

**Comment by alanpepperprof** [comment]
I support the addition of basic stats for Attendance. At the very least, for each attendance item (e.g. Week 1), the stats that Austin suggested:

- Created date
- created by
- modified Date
- modified by

This is very helpful when it comes to troubleshooting issues. We saw a situation in sites that were automatically created with the content copy process (to populate attendance items). A few days later in only a small number of sites, the pre-populated items disappeared. We had no idea what happened. Was it a course creation hiccup? Was it an underlying bug in the system? Did one of the several TAs delete stuff by mistake? The basics of the what, who, and when can be very helpful when tracking down issues.

Moving beyond this, in Gradebook there is a Grade Log. This is helpful for professors to verify that they indeed granted extra points after a conversation with a student, as well as checking who changed a grade (did a TA overwrite a professor?). Similarly, it would be helpful to have a feature similar to the Gradebook Grade Log or more like the User Audit Log in Site Info to track who assigned grades per attendance item. In larger GE classes where there may be one professor and multiple TAs, this can help keep track of changes for attendance.

**Comment by ottenhoff** [comment]
I've added lastModifiedBy and lastModifiedDate and also two events are now posted when events of rules are deleted. I think this solves most tracking use cases. 

We could definitely open up a new issue to look at implementing a log like Grades. I would argue that Grades are high-stakes and attendance is significantly less high-stakes. The overall grade is important but tracking present/late via a log seems like a bit of overkill to me. Why not track who changed the assignment instructions or edited the site info overview? The implementation here should solve most mysteries about what TA or Instructor to blame for the mistake.
