### ISSUE TITLE
Simpledateformat in PDF export is using week year instead of year

### ISSUE THREAD

**Issue by davidpbauer** [sakaicontrib/attendance#11]
The simple date format used for the PDF export feature is using 'YYYY' (Week Year) instead of 'yyyy' (Year). This is not a major issue but could cause the dates to look wrong for items with a date during the last week in Dec. / first week in Jan.

Reported by:
Austin, Sammy Lee, and Kenwrick Chan from The University of Hawai‘i.

**Comment by ottenhoff** [comment]
Submitted PR #42 

Review would be appreciated

**Comment by ottenhoff** [comment]
PR merged
