### ISSUE TITLE
Export all to CSV

### ISSUE THREAD

**Issue by ottenhoff** [sakaicontrib/attendance#21]
New feature request we're hearing from clients: need ability to export all data to CSV including comments.

**Comment by ottenhoff** [comment]
Hi @davidpbauer this import/export you built at UD looks pretty great. Can you point us to the relevant code? Can we work on getting it PRed into this this repo?

**Comment by davidpbauer** [comment]
Hi @ottenhoff , the branch we are running in production that has this feature is here if you'd like to take a look yourself. https://github.com/UDayton/attendance/commits/isidore.

It's really the only change we've made in a while (it was done by our student worker during the summer). On the Isidore branch, the commits from Jul 6, 2017, onward would be relevant (except for the obvious 12 upgrade stuff). I can create a pull request with the relevant changes this week.

**Comment by davidpbauer** [comment]
Hey Sam, I found out today that I'll be out of the office starting tomorrow until Feb. 11 but will pick this back up when I return.

**Comment by ottenhoff** [comment]
Thanks no rush here

**Comment by mpellicer** [comment]
Hi @davidpbauer, one client requested this feature and I saw your video, it looks good, thanks!

As you probably didn't have the chance to take a look, I'm willing to help, I've applied all this commits in a recent branch and my tests were good:

https://github.com/UDayton/attendance/commit/73332b787e330c8046d9cabedaf4acd892a40672
https://github.com/UDayton/attendance/commit/9ef9391e3777c6030824ff4174e4ef63c0a77212
https://github.com/UDayton/attendance/commit/3eca2feb7eedad817644336b93a8938d2112fcb0
https://github.com/UDayton/attendance/commit/2ea04ac77b1864284127356263abb952b336d6fe

I did this PR with all the commits and the fixes:
https://github.com/sakaicontrib/attendance/pull/46

Hope this helps, as far as I can tell, all my tests were good.

**Comment by davidpbauer** [comment]
Thanks, @mpellicer! The PR looks fine to me.

**Comment by mpellicer** [comment]
Merged into Master, thanks @davidpbauer  and @ottenhoff

**Comment by mpellicer** [comment]
After testing it in Master, you can close this GitHub issue. I'd love to receive some feedback.
