### ISSUE TITLE
20170215 release has no conversion for attendance_item_stats_t

### ISSUE THREAD

**Issue by ottenhoff** [sakaicontrib/attendance#25]
It seems like attendance_item_stats_t was added for performance reasons. But there is no conversion routine to aggregate the old data.

Is Dayton running the latest code in production? Do you have SQL commands to aggregate the old data into attendance_item_stats_t?

**Comment by master-bob** [comment]
Old data was calculated live. 

Please see the [following](https://github.com/sakaicontrib/attendance#performance-improvements---must-read).

**Comment by ottenhoff** [comment]
Okay, thanks for the pointer. 

I think the use of a calculation table is a mistake. You now have two sources of truth: the records table and the calculation table. With good indexes on your tables, it should be possible to calculate the stats for an entire class in under a second. The gradebook does very similar calculations without relying on a calculations table.

**Comment by master-bob** [comment]
There is one source of truth (the Attendance Records), and one convenience table.

But overall, I do agree. The creation of the statistics tables was a result of me not fully understanding the performance issues.

**Comment by ottenhoff** [comment]
Was the 20170215 only to add these new aggregate tables? Does it make any sense to think about reverting and going back to simpler times?

**Comment by master-bob** [comment]
Please see the [changelog](https://github.com/sakaicontrib/attendance/blob/v20170215/CHANGES.md#20170215).
