### ISSUE TITLE
Quartz job will run on every site getAttendanceSiteBatch

### ISSUE THREAD

**Issue by ottenhoff** [sakaicontrib/attendance#27]
getAttendanceSiteBatch: SELECT id FROM AttendanceSite attendanceSite WHERE (attendanceSite.syncTime IS NULL OR attendanceSite.syncTime < :syncTime)

I believe this should limit based on published status at a minimum.

**Comment by master-bob** [comment]
So do a Join with SAKAI_SITE where Published = 1. This would be a beneficial improvement.

**Comment by ottenhoff** [comment]
I no longer see getAttendanceSiteBatch in master
