### ISSUE TITLE
Datetime problem

### ISSUE THREAD

**Issue by kolkhetian** [sakaicontrib/attendance#30]
In Attendance tool, when i enter attendance item for after 29 October it saving item's hour an hour more (e.g 10.11.2017 10:30 becomes 10.11.2017 11:30), when i want to update, it brings the hour normally but date appear as one day back (e.g 10.11.2017 10:30 becomes 09.11.2017 10:30). DST is no longer used in Turkey and now using utc +3 as standard. Therefore i updated JVM with tzupdater (with https://www.iana.org/time-zones/repository/tzcode-latest.tar.gz) and when i checked, everything seems properly in followed output. Is there any solution proposal that has encountered the same problem in the past or these times?

sun.util.calendar.ZoneInfo
[
	id="Europe/Istanbul",
	offset=10800000,
	dstSavings=0,
	useDaylight=false,
	transitions=130,
	lastRule=null
]

**Comment by kolkhetian** [comment]
The cause of the problem was the Joda library. I solved the problem by updating Joda.

**Comment by ottenhoff** [comment]
Where does Attendance use Joda?

**Comment by kolkhetian** [comment]
Hi again,
You right, the Attendance tool does not use Joda directly but the DateTimeField class (_org.apache.wicket.extensions.yui.calendar_) is using Joda library. Correct me please if i am wrong. In fact, the problem is not directly related to the Attendance tool, but when debugging i noticed that the problem is related to joda. The problem was solved when i updated Joda.
