### ISSUE TITLE
Class of 700 students results in 50k queries

### ISSUE THREAD

**Issue by ottenhoff** [sakaicontrib/attendance#44]
Loading attendance in one large site (700 students) with dozens of attendance items results in approximately 50k SQL queries.

<img width="1503" alt="screen shot 2019-01-22 at 1 59 28 pm" src="https://user-images.githubusercontent.com/810505/51558674-0d3e9b80-1e4e-11e9-8957-00ab2e30563d.png">

```java
113     private void createStatusRadio(final Form<AttendanceRecord> rF) {
114         AttendanceStatusProvider attendanceStatusProvider = new AttendanceStatusProvider(attendanceLogic.getCurrentAttendanceSite(), AttendanceStatusProvider.ACTIVE);
115         DataView<AttendanceStatus> attendanceStatusRadios = new DataView<AttendanceStatus>("status-radios", attendanceStatusProvider) {
116             @Override
117             protected void populateItem(Item<AttendanceStatus> item) {
118                 final Status itemStatus = item.getModelObject().getStatus();
```

**Comment by ottenhoff** [comment]
@davidpbauer what about just pre-loading all of the possible results instead of doing it radio by radio?

**Comment by davidpbauer** [comment]
This doesn't fix the problem but I've added paging to the table and made it show 25 records per page in order to speed it up. https://github.com/sakaicontrib/attendance/pull/72

**Comment by austin48** [comment]
Would it be possible to display a dropdown to choose how many students to display?  e.g. 25, 50, 100, 200?  and still do paging, but show the selected amount of students per page that was selected?  Or would that still generate too many queries?
