### ISSUE TITLE
AttendanceStatus incorrect EqualsAndHashcode for entity with its own unique id

### ISSUE THREAD

**Issue by ern** [sakaicontrib/attendance#45]
Given an AttendanceStatus like:
`{id = 0, isActive = 1, status = ‘LATE’, sortOrder = 0, attendanceSite = 1234}`

the Equals and Hashcode would be different for an entity with the same id but a different status like
`{id = 0, isActive = 0, status = ‘LATE’, sortOrder = 0, attendanceSite = 1234 }`

Given the entity has its own unique id it probably makes sense that the EqualsAndHashcode be representative of that
`@EqualsAndHashCode(of = "id")`

**Comment by ottenhoff** [comment]
Can you submit this as a PR?
