### ISSUE TITLE
No suitable method found for addExternalAssessment

### ISSUE THREAD

**Issue by eemirtekin** [sakaicontrib/attendance#48]
Hi All,
I use Sakai 12.5 in production server, and I want to install attendace tool.
I forked attendace tool, and I changed version from 12-SNAPSHOT to 12.5 in pom.xml
And I run below code in attendace directory, but I'm gettin getting error[1]

mvn clean install sakai:deploy -Dmaven.tomcat.home=/opt/tomcat -Dsakai.home=/opt/tomcat/sakai -Djava.net.preferIPv4Stack=true -Dmaven.test.skip=true 

Apache Maven 3.3.9
java version "1.8.0_171"

Any help?

[1]

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project attendance-impl: Compilation failure: Compilation failure:
[ERROR] /root/gtu/attendance/impl/src/java/org/sakaiproject/attendance/impl/AttendanceGradebookProviderImpl.java:[77,34] no suitable method found for addExternalAssessment(java.lang.String,java.lang.String,<nulltype>,java.lang.String,java.lang.Double,<nulltype>,java.lang.String,<nulltype>,boolean,<nulltype>)
[ERROR] method org.sakaiproject.service.gradebook.shared.GradebookExternalAssessmentService.addExternalAssessment(java.lang.String,java.lang.String,java.lang.String,java.lang.String,double,java.util.Date,java.lang.String) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] method org.sakaiproject.service.gradebook.shared.GradebookExternalAssessmentService.addExternalAssessment(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.Double,java.util.Date,java.lang.String,java.lang.Boolean) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] method org.sakaiproject.service.gradebook.shared.GradebookExternalAssessmentService.addExternalAssessment(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.Double,java.util.Date,java.lang.String,java.lang.Boolean,java.lang.Long) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] /root/gtu/attendance/impl/src/java/org/sakaiproject/attendance/impl/AttendanceGradebookProviderImpl.java:[123,38] no suitable method found for updateExternalAssessment(java.lang.String,java.lang.String,<nulltype>,<nulltype>,java.lang.String,java.lang.Double,<nulltype>,boolean)
[ERROR] method org.sakaiproject.service.gradebook.shared.GradebookExternalAssessmentService.updateExternalAssessment(java.lang.String,java.lang.String,java.lang.String,java.lang.String,double,java.util.Date) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] method org.sakaiproject.service.gradebook.shared.GradebookExternalAssessmentService.updateExternalAssessment(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.Double,java.util.Date,java.lang.Boolean) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :attendance-impl
[root@sakai attendance]# vim pom.xml

**Comment by ottenhoff** [comment]
I recommend using the 12.x maintenance branch:

https://github.com/sakaicontrib/attendance/tree/12.x

If you want to use Sakai 12.5 and not 12.6, you would need to use this Git commit:

https://github.com/sakaicontrib/attendance/commit/76bd548008170514418189e1c69982193636aabd

**Comment by eemirtekin** [comment]
Hi @ottenhoff 
I have already use 12.x maintenace branch for attendace.
I've changed from 12-SNAPSHOT to 12.5 before, I left it (12-SNAPSHOT) as it is now

[root@sakai gtu]# git clone https://github.com/sakaicontrib/attendance.git
Cloning into 'attendance'...
Resolving deltas: 100% (2293/2293), done.

[root@sakai gtu]# cd attendance/
[root@sakai attendance]# git checkout 12.x
Branch 12.x set up to track remote branch 12.x from origin.
Switched to a new branch '12.x'
[root@sakai attendance]# git checkout 12.x
Already on '12.x'

[root@sakai attendance]# mvn clean install sakai:deploy -Dmaven.tomcat.home=/opt/tomcat -Dsakai.home=/opt/tomcat/sakai -Djava.net.preferIPv4Stack=true

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.sakaiproject.attendance:attendance:20180412: Could not find artifact org.sakaiproject:master:pom:12-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 29, column 10
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.sakaiproject.attendance:attendance:20180412 (/root/gtu/attendance/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.sakaiproject.attendance:attendance:20180412: Could not find artifact org.sakaiproject:master:pom:12-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 29, column 10 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
