### ISSUE TITLE
export / import fails

### ISSUE THREAD

**Issue by austin48** [sakaicontrib/attendance#59]
Export / Import fails with different symptoms depending on the version.

In **12.x**

- export seems ok but if you did not select any export options, when you try to import there will be an error
- `Caused by: java.lang.IndexOutOfBoundsException: Index: 4, Size: 4`

In **19.x** @mpellicer saw that
- export throws a stack trace
- `28-Aug-2019 14:09:49.372 ERROR [http-nio-8080-exec-6919] org.apache.wicket.DefaultExceptionMapper.mapUnexpectedExceptions Unexpected error occurred
org.apache.wicket.WicketRuntimeException: Method onLinkClicked of interface org.apache.wicket.markup.html.link.ILinkListener targeted at [DownloadLink [Component id = submit-link]] on component [DownloadLink [Component id = submit-link]] threw an exception
        at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:268)
        at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:216)`
.
.
.
`Caused by: java.lang.NullPointerException
        at org.sakaiproject.attendance.tool.pages.ExportPage.buildExcelFile(ExportPage.java:174)`
- and that error is related to [commit](https://github.com/sakaicontrib/attendance/commit/66d37986b3c1d7d3c86e77d308d2dadf937e3c53#diff-72f27be9be2c28b8daa2d420651dba6f)

In **master** 
- export seemed ok, but import failed with the warning message
- `Please check your spreadsheet for misaligned data in the Attendance item columns.
No changes were found in the import file.`
`No active students are in this site or group. 
You can add students to the site or a group via the Site Info tool`
- even though the spreadsheet contained changes and active students

**Comment by davidpbauer** [comment]
@jkozar2 has fixed the bugs with import/export for the master version of the project https://github.com/sakaicontrib/attendance/pull/60. This work may be possible to merge back to the other versions but I haven't done any testing with that.
