### ISSUE TITLE
[Feature Request] Attendance should use Sakai's datepicker.

### ISSUE THREAD

**Issue by mpellicer** [sakaicontrib/attendance#76]
Currently it's using Wicket's datepicker instead of Sakai's datepicker, for consistency reasons it should use the same picker:

![image](https://user-images.githubusercontent.com/8653754/108507707-ff70d400-72ba-11eb-9c9d-c1dd1caf2972.png)

**Comment by ottenhoff** [comment]
My wicket 9 PR addresses this
